#!/usr/bin/env python3
"""Insert English customer strings into text.json without touching fa.Admin."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
path = ROOT / "text.json"

en_users = {
    "Rules": "✅ Rules accepted. You can now use the bot.",
    "back": "Returned to the main menu!",
    "backbtn": "🏠 Back to main menu",
    "backmenu": "🏠 Back to previous menu",
    "time-Service": "⏳ Subscription duration",
    "listusers": "📌 Choose one of the methods below to view users.",
    "Volume-Service": "🌐 Service volume",
    "selectoption": "Select an option",
    "selectusername": "Send a custom username\n⚠️ The username must not include extra characters such as @, spaces, or hyphens.\n⚠️ The username must be in English.\n✅ Valid usernames: ali12  | mahdi  | ws1_ksdf\n❌ Invalid usernames: ali_ |  tele@  |  _mahdi | mohsen",
    "invalidusername": "❌ Invalid username\n🔄 Please send your username again",
    "SendMessage": "📩 Send a message to the user",
    "erroroccurred": "❌ An error occurred. Please start over.",
    "customusername": "Custom username",
    "disable": "Disabled",
    "spam": {
        "spamed": "Sending too many messages in the bot",
        "spamedmessage": "📌 Your account has been blocked for spamming the bot.",
        "spamedreport": "User with ID %s was blocked for spamming the bot",
    },
    "block": {
        "descriptions": "🚫 You have been blocked by the administrator.\n\n✍️ Reason:  %s"
    },
    "channel": {
        "link": "Not set",
        "text_join": "🔗 Join the channel",
        "confirmjoin": "✅ Check membership",
        "confirmed": "Your membership was confirmed. Thank you ❤️",
        "notconfirmed": "❌ You have not joined the channel yet.",
        "left_channel": "❌ You left our channel and will miss news and updates. Please join the channel again.",
    },
    "affiliates": {
        "affiliatesyou": "❌ You are already a referral of user %s and cannot join another user.",
        "affiliatesidyou": "❌ You cannot become a referral with this user ID.",
        "setpercentage": "📌 Send the percentage you want credited to the user after a purchase",
        "changedpercentage": "✅ Referral payout percentage was set",
        "banner": "⭕️ Send your referral banner\n\n❌ The banner must include a photo",
        "invalidbanner": "❌ Invalid banner (it must be sent with a photo)",
        "insertbanner": "✅ Your banner was saved.",
        "invalidaffiliates": "❌ You cannot refer yourself",
        "priceDiscount": "📌 Enter the amount a user should receive for each new referral",
        "changedpriceDiscount": "✅ Referral bonus amount was saved",
        "offaffiliates": "❌ The referral program is currently disabled",
        "affiliateedago": "❌ You have already been referred by another user and cannot join again",
        "affiliateinfo": "🤔 How does the referral program work?\n\n👨🏻‍💻 You can grow your wallet balance and use the bot without paying us anything.\n\n👥 Invite friends with your personal link and earn commission on their purchases.\n\n👤 Use the banner above to collect referrals.\n\n💵 Bonus per signup: %s Toman\n💴 Commission on referral purchases: %s%%\n\n📊 Your stats\n• Users who joined with your link: %s\n• Number of purchases: %s\n • Purchase amount: %s Toman",
    },
    "number": {
        "false": "❌ Invalid phone number. Please send it using the button below.",
        "Warning": "⚠️ Could not save the phone number. It must belong to this Telegram account.",
        "erroriran": "⭕️ Invalid mobile number. Only Iranian numbers are accepted.",
        "active": "✅ Your mobile number was verified",
        "Confirming": "📞 Please send your mobile number for verification using the button below",
    },
    "sell": {
        "deactivepanel": "❌ Sales are currently disabled",
        "service_not_available": "⛔️ You have no active services",
        "service_sell": "🛍 Subscriptions you purchased\n\n⚠️ Tap a username to view details and manage the service\n\n⭕️ You can also use \"🔎 Quick search\" to find a service faster",
        "Service-select": "🛍️ Please select the service you want to buy!",
        "error-product": "❌ The selected product does not exist",
        "Service-select-first": "🛍️ Please select the service you want to buy!",
        "None-credit": "📝 Your balance is not enough. Choose a payment method from the list below",
        "ErrorConfig": "❌ An error occurred while creating the subscription. Please contact support.",
        "selectpayment": "📌 Choose a payment method from the list above",
        "notestep": "📌 Write a note for your config.\n⚠️ This name is used to find the service faster later\n🪪 (example: Ali, office, travel, ...)",
    },
    "stateus": {
        "notUsernameget": "Username does not exist",
        "SendUsername": "📌 Send your username",
        "active": "✅ Active",
        "limited": "🚫 Data limit reached",
        "disabled": "❌ Disabled",
        "expired": "🔚 Service expired",
        "on_hold": "❌ Not connected",
        "Unknown": "❌ Unknown",
        "Unlimited": "Unlimited",
        "month": " month ",
        "day": " day ",
        "hour": " hour ",
        "min": "minute",
        "Notconsumed": "Not used",
        "username": "Username: ",
        "stateus": "Status:",
        "expirationDate": "Expires:",
        "daysleft": "Time remaining:",
        "usedTrafficGb": "Data used:",
        "LastTraffic": "Total data: ",
        "RemainingVolume": "Data remaining: ",
        "info": "📊 Service details:",
        "error": "❌ An error occurred",
        "panelNotConnected": "❌ Service lookup is currently unavailable. Please try again later.",
        "UserNotFound": "❌ This service was not found on the server!",
        "statusdisable": "❌ This service is disabled, so details cannot be shown",
        "errorexits": "❌ A request already exists for this username. You cannot submit a new one.",
        "errorusertest": "❌ Refunds are not available for test accounts.",
        "getlinksub": "🔗 Get subscription link",
        "linksub": "🔗 Subscription link",
        "backlist": "🏠 Back to service list",
        "backservice": "🏠 Back to service details",
        "backinfo": "↪️ Back",
        "Invalidusername": "❌ Invalid username.\n🔄 Please send your username again",
        "config": "🔰 Get config",
        "removeservice": "❌ Request refund",
        "descriptions_removeservice": "📌 Tapping \"✅ I want to delete this service\" will send a deletion request to the admin. After review, the service will be cancelled.\n\n❌ If approved, the unused amount will be credited to your wallet.\n\nThank you for using our services.",
        "sendrequestsremove": "✅ Your request was sent. You will be notified after the admin reviews it.",
        "exitsrequsts": "❌ You already have a pending request. Wait for it to be reviewed before submitting a new deletion request.",
        "requestadmin": "📌 Deletion rejection was recorded. Send the reason for rejection.",
        "accecptreqests": "✅ Saved successfully",
        "disabledconfig": "❌ Your service was disabled.",
        "activedconfig": "✅ Your service was enabled",
        "notchanged": "❌ The service status cannot be changed.",
    },
    "extend": {
        "title": "💊 Renew service",
        "titleBtn": "♻️ Renew service",
        "confirm": "Confirm renewal",
        "discount": "🎁 Apply discount code",
        "thanks": "🙏 Thank you for renewing.\n\n✅ Your renewal was completed.\n⬅️ Use the buttons below to return to your services or view details.",
        "error": "🚫 Something went wrong. Please contact support.",
        "selectservice": " 🛍 Select a product to renew",
        "selectOrderDirect": "📌 Select the service you want to renew.",
        "emptyServiceforExtend": "❌ You have no services to renew.",
        "renewalerror": "❌ A renewal error occurred. Please try again.",
        "inactivepanel": "❌ Renewal is not available on this panel",
        "inactiveproduct": "❌ This product is disabled and cannot be renewed",
        "renewalinvoice": "📜 Renewal invoice created for username %s.\n\n🛍 Product: %s\n💸 Renewal price: %s\n⏱ Duration: %s days\n🔋 Data: %s GB\n✍️ Description: %s\n💸 Wallet balance: %s\n\n✅ Tap the button below to confirm and renew",
        "autorenew_on": "✅ Auto-renew",
        "autorenew_off": "❌ Auto-renew",
        "autorenew_enabled": "✅ Auto-renew was enabled for this service.\n\n📌 When remaining data reaches the cron warning threshold, the service is renewed with the same plan and the amount is deducted from your wallet.",
        "autorenew_disabled": "❌ Auto-renew was disabled for this service.",
        "autorenew_insufficient": "Your wallet balance is not enough for auto-renew",
        "autorenew_prewarn": "Service %s has auto-renew enabled, but your wallet balance is too low. Please add at least %s to your wallet for a successful renewal.",
        "autorenew_success": "✅ Service %s was renewed automatically.\n\n🛍 Plan: %s\n💸 Amount deducted: %s Toman",
        "autorenew_noproduct": "❌ No matching plan was found for auto-renew.",
        "autorenew_cron_off": "💡 Enable auto-renew and keep your wallet funded to stay connected",
        "autorenew_cron_on": "✅ Auto-renew is enabled for this service.",
        "autorenew_cron_enable": "✅ Enable auto-renew",
    },
    "Extra_volume": {
        "SetPrice": "⭕️ Send the price you want for each extra GB.",
        "ChangedPrice": "✅ Amount saved.",
        "gettypeextra": "📌 Which user type should this price apply to?\nUser types:\nf = regular user\nn = agent\nn2 = advanced agent",
        "sellextra": "➕ Buy extra data",
        "extracheck": "Confirm and add extra data",
        "invalidprice": "🚫 Minimum extra data is 1 GB",
        "setpricerxtratime": "Send the price you want for each extra day",
        "extravolumeinvoice": "📇 Extra data invoice created.\n\n💰 Price per extra GB: %s Toman\n📝 Invoice total: %s Toman\n📥 Requested extra data: %s GB\n\n✅ Tap the button below to pay and add the data.",
        "enterextravolume": "🔋 Enter the extra data you want (in GB):\n\n📌 Price per GB: %s Toman",
    },
    "Extra_time": {
        "title": "⏳ Buy extra time",
        "extratimecheck": "Confirm and add extra time",
    },
    "usertest": {
        "limitwarning": "⚠️ You have reached the test subscription limit.",
        "limitwarningactive": "The test account limit is {limit} account(s) every 10 days. You already have an active test account. Please try again in a few days.",
        "errorcreat": "❌ An error occurred while creating the subscription. Please contact support.",
        "iduser": "User ID",
        "phonenumber": "User phone number",
        "namepanel": "Panel name",
    },
    "help": {
        "disablehelp": "The help section is currently disabled. 😔",
        "btninlinebuy": "📚 View usage guide ",
    },
    "support": {
        "sendmessageadmin": "🚀 Your message was sent. Please wait for a reply.",
        "answermessage": "Reply to message",
        "sendmessageuser": "📨 Send your message to contact support",
        "btnsupport": "☎️ Frequently asked questions are under the FAQ button. Tap it first; if you still need help, tap Support.",
    },
    "Balance": {
        "errorprice": "❌ Error\n💬 Please enter numbers only",
        "selectPatment": "💵 Choose your payment method",
        "nowpayments": "❌ Error\n    The minimum amount for this gateway is 1 USD.",
        "zarinpal": "❌ Error\n    The minimum amount for this gateway is 5000 Toman.",
        "linkpayments": "Creating payment link...",
        "payments": "Pay",
        "changeto": "❌ Error\n    The minimum amount for this gateway is 2 TRX.",
        "errorLinkPayment": "❌ An error occurred while creating the payment link. Please contact support.",
        "reject_pay": "❌ Reject payment",
        "addbalamceuser": "⭕️ Add balance manually",
        "blockedfake": "⭕️ Block user",
        "Confirmpayadmin": "⭕️ This payment was already confirmed",
        "finished": "Your payment was confirmed",
        "sending": "Payment received and is being reviewed. Please wait.",
        "expired": "The payment link has expired and cannot be reviewed",
        "refunded": "The amount was returned to your wallet",
        "waiting": "Waiting for payment confirmation",
        "Failed": "⭕️ Your payment was not confirmed",
        "Confirmpay": "✅ Your payment was successful and the amount was added to your balance",
        "Invalid-receipt": "Invalid receipt. Please send a photo only.",
        "Confirmpaying": "✅ Confirm payment",
        "Send-receipt": "🚀 Your payment receipt was sent. After admin approval, the amount will be added to your wallet.",
        "Send-receiptadnsendconfig": "🚀 Your receipt was sent. After review, the service details will be sent to you.",
        "maxpurchasereached": "❌ You have reached your purchase limit. Top up your wallet first, then buy or renew a service.",
        "insufficientbalance": "❌ Your balance is not enough to buy this service.\n💸 Enter an amount in Toman to top up:\n✅ Minimum %s Toman, maximum %s Toman",
        "receiptimage": "🖼 Receipt image",
    },
    "Discount": {
        "getcode": "💝 Send your gift code to receive credit",
        "notcode": "❌ Invalid code",
        "getcodesell": "🧑‍💻 Send your discount code",
        "erorrlimit": "❌ This discount code has reached its usage limit",
        "erorrlimitdiscount": "❌ This gift code has reached its usage limit",
        "firstdiscount": "❌ This discount code is for first-time purchases only.",
        "gift-deposit": "🎁 %s Toman was added to your account as a deposit bonus.",
        "discountapplied": "Congratulations 🎉\n📌 Your purchase received a %s percent discount",
        "giftcodeused": "⭕️ User @%s (ID %s) used gift code %s.",
        "giftcodesuccess": "Gift code applied. %s Toman was added to your balance. 🥳",
        "giftcodeonce": "📌 This code can only be used once.",
    },
    "changelink": {
        "btntitle": "⚙️ Change link",
        "warnchange": "⚠️ Updating the subscription link will disconnect previous configs. Tap the button below to confirm.",
        "confirm": "Change connection link",
        "confirmed": "✅ Your connection link was updated and the previous config was disconnected. Open service settings to get the new config.",
    },
    "customsellvolume": {
        "title": "⚙️ Custom service"
    },
    "customvolume": {
        "SetPrice": "⭕️ Send the price you want for each custom GB.",
        "setpricetime": "📌 Set custom-service months and price multipliers in the web panel (Custom service tab).",
        "time": "📌 Custom-service month options are set in the web panel.\n⚠️ Each month equals 30 days",
        "savedtime": "✅ Duration saved",
    },
    "search": {
        "title": "🔎 Quick search",
        "usernamgeget": "📌 Send your username",
    },
    "Major": {
        "title": "📌 Send how many services you want to buy\n⚠️ Minimum 1, maximum 15",
        "invalidcount": "❌ You can buy between 1 and 15 services",
    },
    "page": {
        "next": "Next",
        "notusernameme": "🔎 My username is not in the list",
        "previous": "Previous",
    },
    "Service": {
        "Location": "📌 Select the service location."
    },
    "qrcode": {
        "configqrcdoeservice": "📷 Config QR code",
        "sendqrcodeconfig": "Your config QR codes 👇",
    },
    "agenttext": {
        "endrequest": "✅ Your request was submitted. You will be notified after review.",
        "requestreport": "❌ You already have a pending request and cannot submit another.",
        "isagent": "❌ You are already an agent and cannot request agency again.",
        "acceptrequest": "✅ Approve request",
        "rejectrequest": "❌ Reject request",
        "agent-request": "📣 A user requested agency. Please review and decide.\n\nUser ID: <code>%s</code>\nUsername: @%s\nAccount name: %s\nNotes: %s",
        "insufficientbalanceagent": "❌ Your balance is not enough to request agency. Top up first, then send the request.\n\n💸 Agency fee: %s Toman",
        "customnameusername": "👤 Choose a custom name",
    },
    "note": {
        "changednote": "✅ Note updated.",
        "ErrorLongNote": "❌ Notes can be at most 150 characters.",
        "SendNote": "📝 Send your new note (maximum 150 characters).",
    },
    "app": {
        "selectapp": "📌 Choose an option to download",
        "appempty": "❌ There are no apps to download.",
    },
    "pricearze": {
        "tether-price": "Current USDT price: %s Toman",
        "tron-price": "Current TRX price: %s Toman",
    },
    "wheel_luck": {
        "notWinner": "🥲 You did not win this time. Try again tomorrow.",
        "wheel-winner": "⭕️ User @%s (ID %s) won the lucky wheel",
        "winner-congratulations": "🤩 Congratulations, you won! %s Toman was added to your account.",
        "already-participated": "❌ You already played today. Try again tomorrow.",
        "feature-disabled": "❌ This feature is currently disabled",
    },
}

en_admin_overlay = {
    "transfor": {
        "title": "🚚 Transfer service to another user",
        "transfornotvalid": "❌ Test services cannot be transferred to another user.",
        "discription": "🛂 To transfer this subscription, you need the destination user's ID.\n\n‼️ Transfer notes:\n1 - Open Wallet to find a user ID\n2 - After transfer, the subscription will be removed from your account.\n\n🆕 Enter the destination user ID:",
        "notusertrns": "❌ No user was found with this ID.",
        "confirm": "✅ Tap the button below to confirm the transfer.",
        "confirmed": "✅ The service was transferred.",
        "notsendserviceyou": "❌ You cannot transfer a service to yourself.",
    },
    "change-location": {
        "title": "🌐 Change location",
        "changedloc": "✅ Your service was moved.",
        "confirm": "✅ Confirm transfer",
    },
    "month": {
        "title": "📌 Select the service duration",
        "1day": "⏳ 1 day",
        "7day": "⏳ 7 days",
        "1": "⏳ 1 month",
        "2": "⏳ 2 months",
        "3": "⏳ 3 months",
        "4": "⏳ 4 months",
        "6": "⏳ 6 months",
        "365": "⏳ 1 year",
        "unlimited": "🔋 Data-only",
    },
    "Product": {
        "nullpProduct": "⭕️ No product was found. Please contact support.",
        "Invalidvolume": "Invalid volume",
        "Invalidtime": "Invalid number of days",
    },
    "Discount": {
        "invalidcodedis": "❌ Invalid discount code",
    },
    "managepanel": {
        "nullpanel": "⭕️ No location was found. Please contact support.",
        "limitedpanel": "❌ This panel is at capacity. Please use another panel.",
        "limitedpanelfirst": "❌ Account creation is at capacity. Please try again later.",
    },
    "agent": {
        "invalidvlue": "⭕️ Invalid input",
        "agenttext": "👋 Welcome to the agency panel",
        "submitusername": "✅ Your username was saved.",
    },
    "SettingPayment": {
        "issetpay": "❌ You have an unconfirmed payment. Wait for it to be reviewed before sending a new one.",
    },
    "ManageUser": {
        "GetTextResponse": "Send your reply message.",
    },
}


def main():
    data = json.loads(path.read_text(encoding="utf-8"))
    data["en"] = {
        "users": en_users,
        "Admin": en_admin_overlay,
    }
    path.write_text(json.dumps(data, ensure_ascii=False, indent=4) + "\n", encoding="utf-8")
    print("Wrote", path)
    print("en.users keys:", len(en_users))


if __name__ == "__main__":
    main()
